async function main() {
  console.log('Hello, World')
}

main()
  .then(() => process.exit(0))
  .catch(console.error)
